### ISSUE TITLE
Please assist with few minor missunderstandings regarding the setCountry and parcel measures

### ISSUE THREAD

**Issue by flyingbaba** [omniva-baltic/omniva-api-lib#22]
Please help us to understand a few small details in your documentation: 

1. Few questions regarding reciever adress:

        $address
            ->setCountry('LT') //set country code

What are these codes standarts ISO3166-1-Alpha-2, WMO, FIPS ? Is there any documentation about that?

            ->setPostcode('72201') //set postcode
            ->setDeliverypoint('city') //set city
            ->setOffloadPostcode('72203') //set terminal post code if sending to parcel terminal
            ->setStreet('Guobu g.'); //set street`

Can we add State / Province, House number and Apartment number to setStreet method in case of the (PK - Parcel machine – courier delivery) service code ?

2. Regarding package measures

` $measures->setLength(9) //dimension in meter`

IMHO 9 meter long parcel in the example is too much. I don't think Omniva will accept that =) Are you sure these dimensions are in meters and not centimeters ? 

3. Is there any way to get more detailed documentation about the whole API ?

**Comment by markakk** [comment]
Hello,

We answer your questions:
1. To function `setCountry('LT')` need to pass country code value (2 letters string).
To function `setPostcode('72201')` need to pass postal code according to the format of that country (LT, EE and FI are "00000", for LV the format is "LV-0000").
To function `setDeliverypoint('city')` need to pass city name (any string up to 80 chars length). Also to this value can add State/Province.
To function `setOffloadPostcode('72203')` need to pass Omniva terminal or Omniva post office code (the "ZIP" value of the list item in https://www.omniva.ee/locations.json).
To function `setStreet('Guobu g.')` need to pass street, house and apartment number (any string up to 80 chars length).

All string values must be in UTF-8.

If the shipment is delivered to the recipient by a courier, then all parameters are required except offloadPostcode (he cant be). If the shipment is delivered to the parcel machine/post office, then only offloadPostcode and country are required (other parameters are optional).

2. Yes, values must be in meters. The example contains illogical values.

3. API documentation can be found under "XML data exchange specification" on this website https://www.omniva.ee/business/parcel/instructions
