### ISSUE TITLE
Few composer package issues

### ISSUE THREAD

**Issue by dbalabka** [omniva-baltic/omniva-api-lib#6]
Please address a few composer package issues:
1. Remove the vendor folder from the repository because the composer installs all required dependencies, and there is no need to commit them into the repository. Otherwise, two copies of required dependencies will be stored in the developer’s project.
2. Specify supported PHP version
2. Specify the license

**Comment by markakk** [comment]
Thanks for your comments. After checking, we can definitely see that these problems exist. We will fix them in the future.

**Comment by markakk** [comment]
Vendor folder removed in v1.0.6.1
Supported PHP version added in v1.0.7
