### ISSUE TITLE
HTML entities should be properly espaced

### ISSUE THREAD

**Issue by dbalabka** [omniva-baltic/omniva-api-lib#8]
Unfortunately, using special chars like "&" lead to error. The library should properly escape all HTML entities using:
1. [htmlentities](http://php.net/manual/en/function.htmlentities.php)
2. or methods that escape all required entities by default (e.g., https://www.php.net/manual/en/domdocument.createtextnode.php, read more https://stackoverflow.com/a/2823328/983577)

To reproduce the problem try to use "&" in the following line: https://github.com/omniva-baltic/omniva-api-lib/blob/master/example/shipment-request.php#L50

**Comment by markakk** [comment]
Thanks. The library has been improved according to your recommendation. PR: #10
